export const flowers: {name: string, img: string}[]= [
    { 'name': 'alpine sea holly', 'img': '/assets/flower-thumbnails/alpine_sea_holly.jpg' },
    { 'name': 'anthurium', 'img': '/assets/flower-thumbnails/anthurium.jpg' },
    { 'name': 'artichoke', 'img': '/assets/flower-thumbnails/artichoke.jpg' },
    { 'name': 'azalea', 'img': '/assets/flower-thumbnails/azalea.jpg' },
    { 'name': 'ball moss', 'img': '/assets/flower-thumbnails/ball_moss.jpg' },
    { 'name': 'balloon flower', 'img': '/assets/flower-thumbnails/balloon_flower.jpg' },
    { 'name': 'barbeton daisy', 'img': '/assets/flower-thumbnails/barbeton_daisy.jpg' },
    { 'name': 'bearded iris', 'img': '/assets/flower-thumbnails/bearded_iris.jpg' },
    { 'name': 'bee balm', 'img': '/assets/flower-thumbnails/bee_balm.jpg' },
    { 'name': 'bird of paradise', 'img': '/assets/flower-thumbnails/bird_of_paradise.jpg' },
    { 'name': 'bishop of llandaff', 'img': '/assets/flower-thumbnails/bishop_of_llandaff.jpg' },
    { 'name': 'black-eyed susan', 'img': '/assets/flower-thumbnails/black-eyed_susan.jpg' },
    { 'name': 'blackberry lily', 'img': '/assets/flower-thumbnails/blackberry_lily.jpg' },
    { 'name': 'blanket flower', 'img': '/assets/flower-thumbnails/blanket_flower.jpg' },
    { 'name': 'bolero deep blue', 'img': '/assets/flower-thumbnails/bolero_deep_blue.jpg' },
    { 'name': 'bougainvillea', 'img': '/assets/flower-thumbnails/bougainvillea.jpg' },
    { 'name': 'bromelia', 'img': '/assets/flower-thumbnails/bromelia.jpg' },
    { 'name': 'buttercup', 'img': '/assets/flower-thumbnails/buttercup.jpg' },
    { 'name': 'californian poppy', 'img': '/assets/flower-thumbnails/californian_poppy.jpg' },
    { 'name': 'camellia', 'img': '/assets/flower-thumbnails/camellia.jpg' },
    { 'name': 'canna lily', 'img': '/assets/flower-thumbnails/canna_lily.jpg' },
    { 'name': 'canterbury bells', 'img': '/assets/flower-thumbnails/canterbury_bells.jpg' },
    { 'name': 'cape flower', 'img': '/assets/flower-thumbnails/cape_flower.jpg' },
    { 'name': 'carnation', 'img': '/assets/flower-thumbnails/carnation.jpg' },
    { 'name': 'cautleya spicata', 'img': '/assets/flower-thumbnails/cautleya_spicata.jpg' },
    { 'name': 'clematis', 'img': '/assets/flower-thumbnails/clematis.jpg' },
    { 'name': "colt's foot", 'img': "/assets/flower-thumbnails/colt's_foot.jpg" },
    { 'name': 'columbine', 'img': '/assets/flower-thumbnails/columbine.jpg' },
    { 'name': 'common dandelion', 'img': '/assets/flower-thumbnails/common_dandelion.jpg' },
    { 'name': 'corn poppy', 'img': '/assets/flower-thumbnails/corn_poppy.jpg' },
    { 'name': 'cyclamen', 'img': '/assets/flower-thumbnails/cyclamen.jpg' },
    { 'name': 'daffodil', 'img': '/assets/flower-thumbnails/daffodil.jpg' },
    { 'name': 'desert-rose', 'img': '/assets/flower-thumbnails/desert-rose.jpg' },
    { 'name': 'english marigold', 'img': '/assets/flower-thumbnails/english_marigold.jpg' },
    { 'name': 'fire lily', 'img': '/assets/flower-thumbnails/fire_lily.jpg' },
    { 'name': 'foxglove', 'img': '/assets/flower-thumbnails/foxglove.jpg' },
    { 'name': 'frangipani', 'img': '/assets/flower-thumbnails/frangipani.jpg' },
    { 'name': 'fritillary', 'img': '/assets/flower-thumbnails/fritillary.jpg' },
    { 'name': 'garden phlox', 'img': '/assets/flower-thumbnails/garden_phlox.jpg' },
    { 'name': 'gaura', 'img': '/assets/flower-thumbnails/gaura.jpg' },
    { 'name': 'gazania', 'img': '/assets/flower-thumbnails/gazania.jpg' },
    { 'name': 'geranium', 'img': '/assets/flower-thumbnails/geranium.jpg' },
    { 'name': 'giant white arum lily', 'img': '/assets/flower-thumbnails/giant_white_arum_lily.jpg' },
    { 'name': 'globe thistle', 'img': '/assets/flower-thumbnails/globe_thistle.jpg' },
    { 'name': 'globe-flower', 'img': '/assets/flower-thumbnails/globe-flower.jpg' },
    { 'name': 'grape hyacinth', 'img': '/assets/flower-thumbnails/grape_hyacinth.jpg' },
    { 'name': 'great masterwort', 'img': '/assets/flower-thumbnails/great_masterwort.jpg' },
    { 'name': 'hard-leaved pocket orchid', 'img': '/assets/flower-thumbnails/hard-leaved_pocket_orchid.jpg' },
    { 'name': 'hibiscus', 'img': '/assets/flower-thumbnails/hibiscus.jpg' },
    { 'name': 'hippeastrum', 'img': '/assets/flower-thumbnails/hippeastrum.jpg' },
    { 'name': 'japanese anemone', 'img': '/assets/flower-thumbnails/japanese_anemone.jpg' },
    { 'name': 'king protea', 'img': '/assets/flower-thumbnails/king_protea.jpg' },
    { 'name': 'lenten rose', 'img': '/assets/flower-thumbnails/lenten_rose.jpg' },
    { 'name': 'lotus', 'img': '/assets/flower-thumbnails/lotus.jpg' },
    { 'name': 'love in the mist', 'img': '/assets/flower-thumbnails/love_in_the_mist.jpg' },
    { 'name': 'magnolia', 'img': '/assets/flower-thumbnails/magnolia.jpg' },
    // { 'name': 'mallow', 'img': '/assets/flower-thumbnails/mallow.jpg' },
    { 'name': 'marigold', 'img': '/assets/flower-thumbnails/marigold.jpg' },
    { 'name': 'mexican aster', 'img': '/assets/flower-thumbnails/mexican_aster.jpg' },
    { 'name': 'mexican petunia', 'img': '/assets/flower-thumbnails/mexican_petunia.jpg' },
    { 'name': 'monkshood', 'img': '/assets/flower-thumbnails/monkshood.jpg' },
    { 'name': 'moon orchid', 'img': '/assets/flower-thumbnails/moon_orchid.jpg' },
    { 'name': 'morning glory', 'img': '/assets/flower-thumbnails/morning_glory.jpg' },
    // { 'name': 'orange dahlia', 'img': '/assets/flower-thumbnails/orange_dahlia.jpg' },
    { 'name': 'osteospermum', 'img': '/assets/flower-thumbnails/osteospermum.jpg' },
    { 'name': 'oxeye daisy', 'img': '/assets/flower-thumbnails/oxeye_daisy.jpg' },
    { 'name': 'passion flower', 'img': '/assets/flower-thumbnails/passion_flower.jpg' },
    { 'name': 'pelargonium', 'img': '/assets/flower-thumbnails/pelargonium.jpg' },
    { 'name': 'peruvian lily', 'img': '/assets/flower-thumbnails/peruvian_lily.jpg' },
    { 'name': 'petunia', 'img': '/assets/flower-thumbnails/petunia.jpg' },
    { 'name': 'pincushion flower', 'img': '/assets/flower-thumbnails/pincushion_flower.jpg' },
    { 'name': 'pink primrose', 'img': '/assets/flower-thumbnails/pink_primrose.jpg' },
    { 'name': 'pink-yellow dahlia', 'img': '/assets/flower-thumbnails/pink-yellow_dahlia.jpg' },
    { 'name': 'poinsettia', 'img': '/assets/flower-thumbnails/poinsettia.jpg' },
    { 'name': 'primula', 'img': '/assets/flower-thumbnails/primula.jpg' },
    { 'name': 'prince of wales feathers', 'img': '/assets/flower-thumbnails/prince_of_wales_feathers.jpg' },
    { 'name': 'purple coneflower', 'img': '/assets/flower-thumbnails/purple_coneflower.jpg' },
    { 'name': 'red ginger', 'img': '/assets/flower-thumbnails/red_ginger.jpg' },
    { 'name': 'rose', 'img': '/assets/flower-thumbnails/rose.jpg' },
    { 'name': 'ruby-lipped cattleya', 'img': '/assets/flower-thumbnails/ruby-lipped_cattleya.jpg' },
    { 'name': 'siam tulip', 'img': '/assets/flower-thumbnails/siam_tulip.jpg' },
    { 'name': 'silverbush', 'img': '/assets/flower-thumbnails/silverbush.jpg' },
    { 'name': 'snapdragon', 'img': '/assets/flower-thumbnails/snapdragon.jpg' },
    { 'name': 'spear thistle', 'img': '/assets/flower-thumbnails/spear_thistle.jpg' },
    { 'name': 'spring crocus', 'img': '/assets/flower-thumbnails/spring_crocus.jpg' },
    { 'name': 'stemless gentian', 'img': '/assets/flower-thumbnails/stemless_gentian.jpg' },
    { 'name': 'sunflower', 'img': '/assets/flower-thumbnails/sunflower.jpg' },
    { 'name': 'sweet pea', 'img': '/assets/flower-thumbnails/sweet_pea.jpg' },
    { 'name': 'sweet william', 'img': '/assets/flower-thumbnails/sweet_william.jpg' },
    { 'name': 'sword lily', 'img': '/assets/flower-thumbnails/sword_lily.jpg' },
    { 'name': 'thorn apple', 'img': '/assets/flower-thumbnails/thorn_apple.jpg' },
    { 'name': 'tiger lily', 'img': '/assets/flower-thumbnails/tiger_lily.jpg' },
    { 'name': 'toad lily', 'img': '/assets/flower-thumbnails/toad_lily.jpg' },
    { 'name': 'tree mallow', 'img': '/assets/flower-thumbnails/tree_mallow.jpg' },
    { 'name': 'tree poppy', 'img': '/assets/flower-thumbnails/tree_poppy.jpg' },
    { 'name': 'trumpet creeper', 'img': '/assets/flower-thumbnails/trumpet_creeper.jpg' },
    { 'name': 'wallflower', 'img': '/assets/flower-thumbnails/wallflower.jpg' },
    { 'name': 'water lily', 'img': '/assets/flower-thumbnails/water_lily.jpg' },
    { 'name': 'watercress', 'img': '/assets/flower-thumbnails/watercress.jpg' },
    { 'name': 'wild pansy', 'img': '/assets/flower-thumbnails/wild_pansy.jpg' },
    { 'name': 'windflower', 'img': '/assets/flower-thumbnails/windflower.jpg' },
    { 'name': 'yellow iris', 'img': '/assets/flower-thumbnails/yellow_iris.jpg' },
]