version: "3"

volumes:
  accuracy-db-volume:

services:
  api:
    build:
      context: ../api/
    container_name: neural-network-app-api
    volumes:
      - type: bind
        source: ../api/
        target: /usr/src
    environment:
      PORT: 8080
      MONGO_HOST: accuracy-db-svc
      USER_NAME: admin-user
      PASSWD: admin-password
      MONGO_PORT: 27017
      CFLAGS: "$CFLAGS -g0 -Wl"
    ports:
      - '8080:8080'
    restart: always

  accuracy-db-svc:
    build:
      context: ./accuracy-db/
    volumes:
      - accuracy-db-volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: nn-app
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-password
    hostname: accuracy-db
    container_name: accuracy-db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin-password
      ME_CONFIG_MONGODB_URL: mongodb://admin-user:admin-password@accuracy-db-svc:27017/
